export enum Genres {
  Comedy = 'Comedy',
  Fantasy = 'Fantasy',
  Crime = 'Crime',
  Drama = 'Drama',
  Music = 'Music',
  Adventure = 'Adventure',
  History = 'History',
  Thriller = 'Thriller',
  Animation = 'Animation',
  Family = 'Family',
  Mystery = 'Mystery',
  Biography = 'Biography',
  Action = 'Action',
  'Film-Noir' = 'Film-Noir',
  Romance = 'Romance',
  'Sci-Fi' = 'Sci-Fi',
  War = 'War',
  Western = 'Western',
  Horror = 'Horror',
  Musical = 'Musical',
  Sport = 'Sport',
}
